# Generated by Django 4.0.4 on 2022-04-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('Enquiry_Date', models.DateTimeField(auto_now_add=True)),
                ('Enquiry_Source', models.CharField(choices=[('Out-bound', 'Out-bound'), ('Exchange(Trade-in)', 'Exchange(Trade-in)'), ('Workshop', 'Workshop')], max_length=30)),
                ('Place', models.CharField(choices=[('Showroom', 'Showroom'), ('Field', 'Field')], max_length=30)),
                ('REG_No', models.CharField(max_length=10)),
                ('Status', models.CharField(choices=[('Enquiry', 'Enquiry'), ('Follow-up', 'Follow-up'), ('Evaluated', 'Evaluated'), ('Quotation', 'Quotation'), ('Booked', 'Booked'), ('Procured', 'Procured'), ('Failed', 'Failed')], max_length=30)),
                ('RF', models.CharField(max_length=30)),
                ('Quoted_Price', models.IntegerField()),
                ('Expected_Price', models.IntegerField()),
                ('Final_Price', models.IntegerField(null=True)),
                ('Brand', models.CharField(max_length=30)),
                ('Varient', models.CharField(max_length=30)),
                ('Y_O_M', models.DateField()),
                ('KMs', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
