# Generated by Django 4.0.4 on 2022-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.CharField(choices=[('HMP Chennai', 'HMP Chennai'), ('Chennai-TVS', 'Chennai-TVS'), ('Allied Gurgaon', 'Allied Gurgaon'), ('Allied Noida', 'Allied Noida'), ('Dhingra Gurgaon', 'Dhingra Gurgaon'), ('Dhingra Faridabad', 'Dhingra Faridabad'), ('Lohia Peeragarhi', 'Lohia Peeragarhi'), ('Lohia Wazirpur', 'Lohia Wazirpur'), ('Lohia Noida', 'Lohia Noida'), ('Mumbai', 'Mumbai'), ('Salem-TVS', 'Salem-TVS'), ('Erode-TVS', 'Erode-TVS'), ('Coimbatore-TVS', 'Coimbatore-TVS'), ('Secunderabad-TVS', 'Secunderabad-TVS'), ('Vijayawada-TVS', 'Vijayawada-TVS'), ('Erode/Salem-TVS', 'Erode/Salem-TVS'), ('Hyderabad-TVS', 'Hyderabad-TVS'), ('Visakhapatnam-TVS', 'Visakhapatnam-TVS'), ('Madurai-TVS', 'Madurai-TVS')], default=False, max_length=30),
        ),
    ]
