# Generated by Django 4.0.4 on 2022-04-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthdate_user_currency_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NAME',
            field=models.CharField(default='Need to write your name', max_length=30),
        ),
    ]
